### ISSUE TITLE
Potential Bottleneck: Throughput of Persistent Disk for NFS

### ISSUE THREAD

**Issue by LiamHe** [mlbench/mlbench#72]
When training models with SGD, we need the following amount of data from the persistent disk per iteration
```
(# processes) * (datapoint bytes) * (batch size)
```
For example, if there are `20` processes and each of them need a minibatch of 32 images (`224*224*3*4 / 1e6` Mb per image), then the disk need to transfer `385.35` Mb. If we use multiple parallel workers to dataset, then we have to multiply it by several times. For [GCE persistent disk](https://cloud.google.com/compute/docs/disks/performance), `read throughput per GB` for `SSD` is `0.48 M/s`. 

A possible way is to increase the volume of persistent disk and thus increase its throughput.
When loading data asynchronously, the influence of throughput can be reduced as well.

Do you think we should fix the throughput of disk for each task?

**Comment by martinjaggi** [comment]
as some best practice, the required data would likely be transferred to some local memory on the node first, before starting the actual training? especially for cifar10 as it will easily fit on each node. 
we'd like to only measure time from when data is distributed properly among the nodes.

but for the proof of concept, we can go with the most convenient way first.

in general i'm not a fan of making the benchmark depend on NFS and other cloud storage systems, since those vary greatly between different cloud services (google, AWS).
nevertheless in terms of size, for imagenet we'll have to discuss this again later quite likely

**Comment by IamTao** [comment]
For cifar10, it would not be an issue. But for ImageNet, using NFS is quite convenient and was what I did in my previous attempts, either GCloud or IC kubernetes cluster.

Maybe for the closed division, we should test the task and make sure throughput would not be the bottleneck. But for open division, users are free to propose different data storage strategies.

**Comment by martinjaggi** [comment]
closing this for now, will revisit likely when imagenet becomes ready
